kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: myconfig # Reference value is from 08-config-map.yaml file